#!/usr/bin/env bash
# This script displays the string "Best School" 10 times but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while [ $1 -le 10 ]; do
    echo "Best School"
    if [ $1 = 9 ]; then
        echo "Hi"
    if
    i=$(( i + 1 ))
done
